GET http://localhost:5000/api/user HTTP/1.1

### Register a user
POST http://localhost:5000/api/user HTTP/1.1
Content-Type: application/json

{
    "username": "testUserTen",    
    "password": "123456"
}

### Login
POST http://localhost:5000/api/user/login HTTP/1.1
Content-Type: application/json

{
    "username": "testUserSix",    
    "password": "123456"
}

### Get all users
GET http://localhost:5000/api/user HTTP/1.1

### Get single user
GET http://localhost:5000/api/user/61ee06142ce9392a507e467b HTTP/1.1